### ISSUE TITLE
not working with latest q2a

### ISSUE THREAD

**Issue by itsbalamurali** [harshjv/q2a-bootstrap#2]
your theme is not working in latest version of q2a.

**Comment by deathbat6661** [comment]
Not working with q2a dev version 1.6
but working perfectly use stable version 1.5.4, just change some code

('QA_VERSION', '1.5.4')
('QA_BUILD_DATE', '2012-11-29')

into file /qa-include/qa-base.php

default in file is
('QA_VERSION', '1.5.3')
('QA_BUILD_DATE', '2012-09-26')
