### ISSUE TITLE
Any updates

### ISSUE THREAD

**Issue by gurjyot** [harshjv/q2a-bootstrap#4]
Hellp harshjv
Are you planning to give any updates on your beautiful theme so that it can be compatible with q2a v1.7 (coming soon).

**Comment by gurjyot** [comment]
Any planned updates on this theme...??

**Comment by harshjv** [comment]
Glad to see that you are interested in this project. But unfortunately, I may not be able to spare time for this project. As you can see, this is more than a year old repo, so I would suggest that, if you can contribute to this project, it would be great.

Sorry for inconvenience.
