### ISSUE TITLE
Missing argument 1 for qa_path_html()

### ISSUE THREAD

**Issue by msampaio** [harshjv/q2a-bootstrap#5]
I tried q2a-bootstrap with q2a 1.7 and I got this message:

`Warning: Missing argument 1 for qa_path_html(), called in .../q2a-bootstrap-master/qa-theme.php on line 76 and defined in .../qa-include/qa-base.php on line 1346`

Is this a bug?

The line [76](https://github.com/harshjv/q2a-bootstrap/blob/master/qa-theme.php#L76):
`.'<a class="navbar-brand" href="'.qa_path_html().'">'.qa_opt('site_title').'</a>'`

and line 1346:
`function qa_path_html($request, $params=null, $rooturl=null, $neaturls=null, $anchor=null)`

**Comment by harshjv** [comment]
Current `master` branch is not ready yet.

If you want to try this theme then use `v1.1.0` of this theme with **Q2A v1.5.3**
